### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by cbobed** [martialblog/word_embedding_storage#7]
Hi Markus, 

First of all, interesting comparison :) 

Back in the day, a colleague of mine tried both mysql and sqlite achieving similar results (a little bit degraded). I was curious, and I've checked the example code but I haven't found any index or primary key created in these two rdbms. Have you tested the performance also including an index for the 'key' field? 

Best

**Comment by martialblog** [comment]
Hey, I haven't tried indexing the keys (most likely improve the read performance). This was just a simple experiment. Personally I use this package for all my word vector needs: https://github.com/plasticityai/magnitude

If you want to extend the code, I'm happy to merge any PR.

**Comment by martialblog** [comment]
Can I help you with anything else? Otherwise I would close this

**Comment by cbobed** [comment]
no, no, thank you very much!
